### ISSUE TITLE
1.19.4 - Paintbrush Not Obtainable [Forge 45.0.29]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SeafoamWolf/SeafoamsDyeableBlocks#4]
![KzJ0cd1 1](https://user-images.githubusercontent.com/10351221/228431259-8ac2be06-ce32-478b-9226-c77dac28af43.png)
![YhnOFf8 1](https://user-images.githubusercontent.com/10351221/228431580-f00eba20-9e52-4bae-9a2b-ddc19711bb2a.png)

**Comment by SeafoamWolf** [comment]
It looks like you're running an older version actually. The recipe for that version is Warm Dye, Cool Dye, Monochrome Dye, and a Color Essence for the Dynamic Dye (what the Paintbrush used to be). Sorry about that!

**Comment by SeafoamWolf** [comment]
I've updated the other versions to match, the brush should be in all of them now.

I changed it to the brush in version 1.1.0, but only Forge 1.19.2 and Fabric 1.19.4 were updated.
They should all be updated on Modrinth already, and Curseforge is just pending approval right now.

You can get the new version for Forge 1.19.4 here: https://modrinth.com/mod/seafoams-dyeable-blocks
