### ISSUE TITLE
this mod is so broken smh

### ISSUE THREAD

**Issue by Dogethebestdoggo** [SeafoamWolf/SeafoamsDyeableBlocks#6]
bro the hell is this mod it doesnt even work im on fabric and i have the version 1.0.0 wich u didnt even update it to 1.2.0 and i have no paintbrush
 smh

**Comment by SeafoamWolf** [comment]
They're all updated now, you should be able to get 1.2.0 on Fabric and Forge, on both 1.19.2 and 1.19.4.

**Comment by Dogethebestdoggo** [comment]
ok but like how does this mod work

**Comment by Dogethebestdoggo** [comment]
i dont understand im right clicking on the dyable block
 tell me how you do this...

**Comment by SeafoamWolf** [comment]
I'm sorry for the confusion, I've been meaning to write this down somewhere.

The only blocks that can be dyed at the moment are
- Wool
- Concrete
- Regular Terracotta
- Any Wood Planks
- Glowstone
- Bricks

I'm not super experienced with in depth mod creation, so I haven't figured out a way to implement blocks without manually adding each one yet, though I'd definitely like to do that in the future.

I'm really sorry for all of the confusion.

**Comment by Dogethebestdoggo** [comment]
you good dw abt it but like i cant dye the blocks at all....
 im pressing right shift with an paint brush
